name: hello-world
on: push
jobs:
    my-job:
        runs-on: ubuntu-latest
        container: gradle6-jdk11
        steps:
            - name: Clone-down
              uses: actions/checkout@v2
              run: chmod +x ci/build-app.sh && ci/build-app.sh
